spring:
  application:
    name: accounts-services
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
      
server:
  port: 2222
  
  error:
    whitelabel:
      enabled: false
      